version: '3.2'
services:
   mysql:
      image: mysql:8.0
      container_name: firstspringbootapp_mysql
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: password
   phpmyadmin:
      depends_on:
       - mysql
      image: phpmyadmin/phpmyadmin
      container_name: firstspringbootapp_phpmyadmin
      restart: always
      ports:
       - '81:80'
      environment:
        PMA_HOST: mysql